### ISSUE TITLE
怎么获取设备的串口号呢？

### ISSUE THREAD

**Issue by lichao315** [licheedev/Modbus4Android#1]
大神，我用Modbus Salve模拟了串口，但是为什么我在模拟器运行程序后，发现串口列表为空呢？
![image](https://user-images.githubusercontent.com/8403808/62751855-da7d8d00-ba97-11e9-937d-4b2a853ac274.png)

![image](https://user-images.githubusercontent.com/8403808/62751885-fb45e280-ba97-11e9-9958-17b7ebc0df58.png)
代码在这里就获取不到串口了

**Comment by licheedev** [comment]
Google官方的模拟器不支持串口。用genymotion+4.4或更老版本模拟器镜像，才能用模拟串口。
参考这里 https://blog.csdn.net/Agou_66/article/details/77878259

**Comment by lichao315** [comment]
![image](https://user-images.githubusercontent.com/8403808/62757189-05bea700-baad-11e9-8522-0104c80d0f26.png)
但是我把你的程序打包成apk后放在平板真机上，也找不到串口，不知道为什么？硬件设备也用USB也插在平板上面了。

**Comment by licheedev** [comment]
@lichao315 你用我另外写的一个工具 https://github.com/licheedev/Android-SerialPort-Tool 看有没有设备列表（虽然感觉希望不大）。
Google的这个串口api是对硬件有要求的，需要设备本身支持驱动串口（或USB串口），
具体就是看存不存在“/dev/ttySx”（可以用adb shell看看），而且需要对这些文件具有读写权限，才能使用串口。
如果都没串口设备列表，只能联系板子的制造商或者换其他板子了。
