### ISSUE TITLE
怎么使用rtu传参

### ISSUE THREAD

**Issue by lichao315** [licheedev/Modbus4Android#2]
您好，我现在收到一份modbus文档（rtu，rs485），如下：
![image](https://user-images.githubusercontent.com/8403808/62918645-e4bec480-bdd2-11e9-9b2f-984a4be788c5.png)
查看您写的api，我不清楚这3个参数该如何对应：
// 普通写法
ModbusManager.get()
    .readHoldingRegisters(mSalveId, mOffset, mAmount,
        new ModbusCallback<ReadHoldingRegistersResponse>() {
            @Override
            public void onSuccess(
                ReadHoldingRegistersResponse readHoldingRegistersResponse) {
                byte[] data = readHoldingRegistersResponse.getData();
                mTvConsole.append("F03读取：" + ByteUtil.bytes2HexStr(data) + "\n");
            }

            @Override
            public void onFailure(Throwable tr) {
                appendError("F03", tr);
            }

            @Override
            public void onFinally() {

            }
        });

其中的mSalveId, mOffset, mAmount怎么对应到我的文档之上，烦请大神解答一下，不胜感激。

**Comment by licheedev** [comment]
slaveId=0x01;
offset=0x0066;
amount=0x0002;
