### ISSUE TITLE
总是报错怎么解决？

### ISSUE THREAD

**Issue by lichao315** [licheedev/Modbus4Android#3]
![image](https://user-images.githubusercontent.com/8403808/63293151-f3890800-c2f9-11e9-84f6-1a2083b1ec9e.png)
代码下载后运行测试，总是走失败的回调，并且报这个错，是怎么回事啊？求解答！

**Comment by licheedev** [comment]
串口配置有没有设置正确？
是不是8n1（8数据位 无校验位 1 停止位）？两个虚拟串口不是参数对应，是不是互联？
![1](https://raw.githubusercontent.com/licheedev/filestore/master/img/modbus4android/serial_setting1.png)
![1](https://raw.githubusercontent.com/licheedev/filestore/master/img/modbus4android/serial_setting2.png)

**Comment by licheedev** [comment]
@lichao315 还有模拟器尽量用Android 4.4或更老版本的系统镜像，那个串口对新系统的支持不是很好。
