### ISSUE TITLE
请教一个问题啊

### ISSUE THREAD

**Issue by lichao315** [licheedev/Modbus4Android#4]
请问您这个库可以直接集成到商用项目里面吗？最近任务太赶了，没空调研了，如果稳定可用的话，我就用您这个直接集成进去了哈？

还有，我想问问，这个modbus-rtu，跟我写的一个串口通信，有什么区别吗，串口通信直接发“01060300014B2C”这样的指令。您这个库，是不是底层还是串口通信，但是上层通过modbus协议的规约，把参数也是转化成指令，通过串口发送吗？

**Comment by licheedev** [comment]
@lichao315 这个项目其实是基于modbus4j，加了个[SerialPortWrapper](https://github.com/licheedev/Modbus4Android/blob/master/modbus4android/src/main/java/com/licheedev/modbus4android/AndroidSerialPortWrapper.java)的实现类，里面用的也是Android的串口。

**Comment by lichao315** [comment]
我们这是串行的，一次收发完之后，才能进行第二次。不知道怎么弄？我看你这个库好像是并行的，是吗？

**Comment by licheedev** [comment]
@lichao315 没有，也是串行，里面用了HandlerThread，就是Handler、Looper、Message那堆东西，也是一次完成后才继续第二次。
不过现在翻看代码，用单线程的线程池+Callable来实现同步，可能更优雅。之前写的时候刚好看过HandlerThread，就试着拿来用，哈哈。

**Comment by lichao315** [comment]
那我连续调用2次发命令的方法呢？比如我发一个03的，这时候03还没有响应完毕，此时我再发送04的指令，这时候会出现什么状况呢？

**Comment by licheedev** [comment]
@lichao315 03执行完，才会执行04的。

**Comment by lichao315** [comment]
![image](https://user-images.githubusercontent.com/8403808/63826704-f9828700-c992-11e9-84f5-19f9df44c2bf.png)
经常的超时yic异常，但是模拟软件上是可以显示数据的。就是收不到啊，总是超时异常。不知道是什么情况，只有偶尔才会接收到数据，很多时候都是超时了。

**Comment by licheedev** [comment]
@lichao315 
F03是读保持寄存器，F04是读输入寄存器，这两种寄存器不是一样的，输入寄存器是只读的，保持寄存器可读可写，你的模拟器建了几个从设备?
好像我这个项目，需要同时操作两种寄存器，就得建两个从设备，同时开着。
![截图](https://raw.githubusercontent.com/licheedev/filestore/master/img/modbus4android/20190828001.png)

**Comment by licheedev** [comment]
@lichao315 同时注意一下设备地址
![截图](https://raw.githubusercontent.com/licheedev/filestore/master/img/modbus4android/20190828002.png)

还有就是提问题，最好说明更详细点，不要吝啬截图，不要吝啬上代码，是真机调试还是用模拟器出现这些问题，模拟器版本是啥，用的什么功能嘛，上面你提供的东西，只有一个F04功能码的异常是有点参考价值的。

**Comment by lichao315** [comment]
不好意思，我重新说明一下啊。我的开发环境是这样，硬件用一个rs485转接头，连在模拟器上。
![image](https://user-images.githubusercontent.com/8403808/63829583-8ed64900-c99c-11e9-9c08-3bffa7216dd4.png)
![image](https://user-images.githubusercontent.com/8403808/63829628-aa415400-c99c-11e9-9a1f-db98b4fafbb1.png)
这就是我的开发环境，首先说明一下，硬件跟模拟器之间是联通的，因为06命令可以正确的执行的。
`我的需求：开机的时候，搜索从机。因为我们这一共可以有12个从机，但是并不一定会全部装上，有时候会装上3个，4个，所以我每次开机的时候，遍历一下从机，就是读一下04的数据，如果有响应我就认为从机是存在的，没有响应就说明从机不存在。但是我检索的时候，发现这个异常，每个从机都是。这就不大合理了好像，因为06命令是正常的。代码如下：  /**
     * 初始化箱体
     */
    private void initBox() {
        showLoadingDialog();
        //首次初始化
        mCategoryInfoList = CategoryUtils.getCategoryInfos();  //取出所有的分类
        mHandler = new MyHandler(OperatorSettingFragment.this);
        mHandler.sendEmptyMessage(0);
    }

    private int mPostion = 0;   //记录当前循环的position

    private static class MyHandler extends Handler {
        private final WeakReference<OperatorSettingFragment> mFragment;

        private static int MAX_SIZE; //记录循环的最大边界

        public MyHandler(OperatorSettingFragment fragment) {
            mFragment = new WeakReference<OperatorSettingFragment>(fragment);
            MAX_SIZE = fragment.mCategoryInfoList.size();
        }

        @Override
        public void handleMessage(Message msg) {
            OperatorSettingFragment fragment = mFragment.get();
            if (fragment != null) {

                int salvedId = fragment.mCategoryInfoList.get(fragment.mPostion).getSalvedId();
//                int salvedId = 1;
                int offset = 0;
                int amount = 45;

                LogUtils.i(TAG, "发命令 ： position=" + fragment.mPostion + ",salveId=" + salvedId);
                ModbusManager.get()
                        .readInputRegisters(salvedId, offset, amount,
                                new ModbusCallback<ReadInputRegistersResponse>() {
                                    @Override
                                    public void onSuccess(
                                            ReadInputRegistersResponse readInputRegistersResponse) {

                                        byte[] data = readInputRegistersResponse.getData();
                                        LogUtils.i(TAG, Thread.currentThread().getName() + "--读取salveId = " + readInputRegistersResponse.getSlaveId() + "地址结果为：" + ByteUtils.byteArrayToHexString(data));
                                        fragment.mCategoryInfoList.get(fragment.mPostion).setUsed(true);
                                        fragment.mPostion++;
                                        if (fragment.mPostion < MAX_SIZE) {  //继续读取
                                            sendEmptyMessageDelayed(0, 50);
                                        } else {
                                            //超出边界，停止读取，保存数据
                                            List<CategoryInfo> list = new ArrayList<>();
                                            for (CategoryInfo info : fragment.mCategoryInfoList) {
                                                if (info.isUsed()) {
                                                    list.add(info);
                                                }
                                            }
                                            if (list.size() > 0) {
                                                String json = JsonUtil.toJson(list);
                                                Preferences.getInstance(fragment.getActivity())
                                                        .putString(Preferences.BOX_CONFIGURATION_INFORMATION, json);
                                                LogUtils.i("OperatorSettingFragment", "数据为=====================");
                                                LogUtils.json("OperatorSettingFragment", json);
                                            }
                                            fragment.mHandler.removeMessages(0);
                                            //通知首页修改分类
                                            EventBus.getDefault().post(new UpdateHomeCateEvent());
                                            fragment.hideLoadingDialog();
                                            TastyToast.makeText(fragment.getActivity(), "初始化完毕！", TastyToast.LENGTH_SHORT, TastyToast.INFO).show();
                                            fragment.mPostion = 0;
                                        }
                                    }

                                    @Override
                                    public void onFailure(Throwable tr) {
                                        LogUtils.i(TAG, Thread.currentThread().getName() + "--初始化箱体错误为：" + tr);
                                        fragment.mCategoryInfoList.get(fragment.mPostion).setUsed(false);
                                        fragment.mPostion++;
                                        if (fragment.mPostion < MAX_SIZE) {  //继续读取
                                            sendEmptyMessageDelayed(0, 50);
                                        } else {
                                            //超出边界，停止读取，保存数据
                                            List<CategoryInfo> list = new ArrayList<>();
                                            for (CategoryInfo info : fragment.mCategoryInfoList) {
                                                if (info.isUsed()) {
                                                    list.add(info);
                                                }
                                            }
                                            if (list.size() > 0) {
                                                String json = JsonUtil.toJson(list);
                                                Preferences.getInstance(fragment.getActivity())
                                                        .putString(Preferences.BOX_CONFIGURATION_INFORMATION, json);
                                                LogUtils.i("OperatorSettingFragment", "数据为=====================");
                                                LogUtils.json("OperatorSettingFragment", json);
                                            }
                                            fragment.mHandler.removeMessages(0);
                                            //通知首页修改分类
                                            EventBus.getDefault().post(new UpdateHomeCateEvent());
                                            fragment.hideLoadingDialog();
                                            TastyToast.makeText(fragment.getActivity(), "初始化完毕！", TastyToast.LENGTH_SHORT, TastyToast.INFO).show();
                                            fragment.mPostion = 0;
                                        }
                                    }

                                    @Override
                                    public void onFinally() {

                                    }
                                });
            }
        }
    }`
就是用Handler每隔50ms控制写，从集合中循环遍历从机地址，执行04命令。不知道有什么问题？模拟器，genymotion，Android 4.4。

**Comment by licheedev** [comment]
@lichao315 那个，先改一下模拟调试程序的配置，别一次读45个寄存器，减少一点看看，看能不能读到。
我这边这个项目，就出现过一个情况，一次不能写入太多的寄存器，否则就出异常，所以我搞了个分批写入的算法。
```
  /**
     * 批量写寄存器
     *
     * @param offset 寄存器开始索引
     * @param values 要写入的寄存器数量
     * @param eachLen 每次最多写多少个寄存器
     * @throws ModbusTransportException
     * @throws ModbusRespException
     * @throws ModbusInitException
     */
    private void writeRegisters(int offset, short[] values, int eachLen)
        throws ModbusTransportException, ModbusRespException, ModbusInitException {

        // 不超过最大值，直接写入饥渴
        if (values.length <= eachLen) {
            // 写入寄存器
            ModbusManager.get().writeRegisters(offset, values);
            return;
        }

        // 写入次数
        int times = (values.length - 1) / eachLen + 1;

        for (int i = 0; i < times; i++) {
            int start = i * eachLen;
            int end = start + eachLen;
            end = end > values.length ? values.length : end;
            short[] sub = Arrays.copyOfRange(values, start, end);
            // 写入寄存器
            ModbusManager.get().writeRegisters(offset + start, sub);
        }
    }
```

同一份代码，Modbus Slave+Genymotion上是可以一次写所有寄存器的，但是放到真机上，一次写太多就异常了。

还有就是硬件开机后，不能马上就操作设备，最好延迟个一两面后再操作。

然后vbox模拟器的串口跟真机连的时候，不能确保数据的可靠性，可能会漏数据，但是真的Android板子的串口跟设备连，就没问题。

**Comment by lichao315** [comment]
我觉得可能是串口堵塞了，这种循环遍历读数据，开始读了一段，然后到后面就开始报异常了，模拟助手上的数据也显示不全，我猜测是数据堵塞了。不知道怎么解决？`SerialParam.create(path, baudrate).setTimeout(500).setRetries(1)`我在这里设置超时时长500ms，即使设置成1000，也不起作用。而且循环读数据的时候，每次间隔1000ms，都不行。我也不知道问题出在哪里？
到底怎么才能做到循环读的操作呢？因为我这里需要做一个读取用户扫描二维码的操作。

**Comment by lichao315** [comment]
小小测试一下，问题就是在循环读取上，经常发生异常，在串口助手上也看不到数据，看起来像阻塞住了。但是使用Android-SerialPort-Tool这个库，似乎都没问题。

**Comment by licheedev** [comment]
@lichao315 你测试的时候，模拟器里面有开着多个串口相关的应用不？有的话，把其他用了串口的应用全卸载掉，只剩下要测试的那个，免得忘记关闭串口导致读取冲突。还有就是在哪里初始化/打开modbus的，是在Application的onCreate()里面不？应用是否有启用多进程（友盟、Bugly之类的第三方库会开多进程，每个进程都会走一遍Application的onCreate()，同样会导致串口被多开）?

0.3版本可以配置打印log，https://github.com/licheedev/Modbus4Android#%E5%8F%AF%E9%80%89%E9%85%8D%E7%BD%AE 你可以搞来看看。

顺便给我看一下使用Android-SerialPort-Tool测试成功时，数据的截图。

**Comment by lichao315** [comment]
我这边的硬件情况是rs-485的半双工，半双工只用一根线完成读写，相当于串行吧，不能同时多个命令进行读写，要命的是，我必须要遍历一下所有的从机，也就是搜索一下设备的在线状态。所以，我想问您，您的库是否支持半双工，是自动支持呢？还是我人为控制发命令控制行为一个伪半双工？
感谢您，非常感谢！无以言表，最近做这个项目挺着急的。

**Comment by licheedev** [comment]
@lichao315 
1. modbus是一个主从应答协议，明确要求请求是串行的，只有主机发起请求，从机才能做应答，从机不能主动发送数据给主机，且主机同一时间只能进行一个请求，即上一个请求没完成（响应或超时），下一个请求不会执行。
[ModbusWorker.java#L53](https://github.com/licheedev/Modbus4Android/blob/master/modbus4android/src/main/java/com/licheedev/modbus4android/ModbusWorker.java#L53)
我这里强制了所有modbus的操作都得在这个线程里面运行。除非你自己调用了syncXxxxxxx()那堆方法，否则不存在多命令同时执行的情况。（话说485不是AB两根线么）就算你用全双工的232，modbus收发数据都是每次请求完成后才会继续下一次请求。遍历从机的时候，就算两次没间隔，命令也不会扎堆同时执行，只会排队一个一个来。

2. 我想看一下，你vbox虚拟机里面的串口参数是怎么配置，还有在我写的那个modbus调试工具，里面的串口地址选的是啥，发出来看一下。

3. Android-SerialPort-Tool测试截图，发一下。

4. 有没有检查过你测试的时候，有没有多app/多进程都打开了modbus用的串口（非常重要）。最好能发一下初始化的代码（在哪初始化）。

5. 可以先不管遍历的逻辑，先确保普通的单条命令能每次都执行成功吧（直接用调试工具）。

**Comment by lichao315** [comment]
好的！非常感谢作者，帮我解决了好多问题。
说明一下：以上我出现的问题，主要是因为调试环境不行。大家在调试的时候，最好选择使用真实的硬件环境调试，用安卓设备+开发板即可，最好不要选择使用安卓模拟器，我使用genymotion调试，我觉得可能是模拟器的对串口支持的不够好，导致串口堵塞、消息中断等各种问题。所以，建议用真实的安卓设备调试。
最后，再次多谢作者的帮助！！！
