### ISSUE TITLE
如何获取 modbus返回的错误code ?

### ISSUE THREAD

**Issue by iamlfc** [licheedev/Modbus4Android#6]
如题  onFailure() 方法中 如何获取到 ModbusRespException 的 exceptionCode!

**Comment by licheedev** [comment]
这样？
```java
        if (tr instanceof ModbusRespException) {
            int code = ((ModbusRespException) tr).getExceptionCode();
        }
```

**Comment by iamlfc** [comment]
感谢回答
好像这个判断进不去  最终执行到 else 判断中    Log.d("--lfc", "没有结果: " + 3 + "");

 onFailure(Throwable tr){
   if (tr instanceof ModbusInitException) {
       Log.d("--lfc", "ModbusInitException: " + 1 + "");
   } else if (tr instanceof ModbusTransportException) {
       Log.d("--lfc", "ModbusTransportException: " + 2 + "");
   } else if (tr instanceof ModbusRespException) {
       byte errorCode = ((ModbusRespException) tr).getExceptionCode();
       Log.d("--lfc", "ModbusRespException: " + errorCode + "");
   } else {
       Log.d("--lfc", "没有结果: " + 3 + "");
   }
}

**Comment by iamlfc** [comment]
感谢回答
好像这个判断进不去 最终执行到 else 判断中 Log.d("--lfc", "没有结果: " + 3 + "");

```java
if (tr instanceof ModbusInitException) {
    Log.d("--lfc", "ModbusInitException: " + 1 + "");
} else if (tr instanceof ModbusTransportException) {
    Log.d("--lfc", "ModbusTransportException: " + 2 + "");
} else if (tr instanceof ModbusRespException) {
    byte errorCode = ((ModbusRespException) tr).getExceptionCode();
    Log.d("--lfc", "ModbusRespException: " + errorCode + "");
} else {
    Log.d("--lfc", "没有结果: " + 3 + "");
}
```

**Comment by licheedev** [comment]
@iamlfc 因为原先这个库的同步方式有点搓（一定要搭配RxJava或者Handler来指定同步方法执行的线程），所以后面被我改成[Callable+Future](https://github.com/licheedev/Modbus4Android/blob/a5ae7063af46970bda15eb5b51772f3dc2226a9f/modbus4android/src/main/java/com/licheedev/modbus4android/ModbusWorker.java#L309)的方式来实现阻塞同步，这样就导致抛出的异常跟原来的不一样
![](https://raw.githubusercontent.com/licheedev/filestore/master/img/modbus4android/pic1.png)
可能会抛出`ExecutionException（java.lang.Throwable#getCause()可以拿出它包裹的异常）`等异常。因为我一般不管异常的类型，所以也没怎么在意这个问题。

**Comment by iamlfc** [comment]
好吧 主要是我想通过错误code 来处理不同的业务逻辑。那我再试试 看有没有其他方法获取到原始的 ModbusRespException 。

**Comment by licheedev** [comment]
@iamlfc 那等一会，我改改源码。

**Comment by iamlfc** [comment]
ok 非常感谢了

**Comment by licheedev** [comment]
@iamlfc 源码改好了，拉一下新的。
```gradle
implementation 'com.github.licheedev:Modbus4Android:1.0.1'
```
现在会对部分异常进行额外处理。
```java
    private <T> T doSync(Callable<T> callable)
        throws InterruptedException, ModbusInitException, ModbusTransportException,
        ModbusRespException, ExecutionException {

        try {
            return mRequestExecutor.submit(callable).get();
        } catch (ExecutionException e) {
            //e.printStackTrace();
            Throwable cause = e.getCause();
            if (cause instanceof ModbusInitException) {
                throw ((ModbusInitException) cause);
            } else if (cause instanceof ModbusTransportException) {
                throw ((ModbusTransportException) cause);
            } else if (cause instanceof ModbusRespException) {
                throw ((ModbusRespException) cause);
            } else {
                throw e;
            }
        }
    }
```

**Comment by iamlfc** [comment]
已经获取成功了 非常感谢！
